<?php if ($this->isApplicable()): ?>

	<?php $_helper = $this->helper('catalog/output'); ?>

	<?php if (!$this->isWithinAvailability()): ?>

		<?php $monthBegin = $this->getMonthNameFromDate($this->getTimeLapseBegin('medium')); ?>
		<?php $monthEnd = $this->getMonthNameFromDate($this->getTimeLapseEnd('medium')); ?>

		<?php if ($this->isWithinAvailability(true)): ?>

			<?php $message = 'Pre-order only - restricted Trusted Shops Buyer Protection. Available from %s to %s.'; ?>
			<div class="messages">
				<p class="notice-msg"><?php echo $_helper->__($message, $monthBegin, $monthEnd); ?></p>
			</div>

		<?php else : ?>

			<?php $message = 'Pre-order only - Trusted Shops Buyer Protection not available. Available from %s to %s.'; ?>
			<div class="messages">
				<p class="error-msg"><?php echo $_helper->__($message, $monthBegin, $monthEnd); ?></p>
			</div>

		<?php endif; ?>

	<?php endif;?>

<?php endif; ?>